---
additionalProperties: false
properties:
  apiVersion:
    type: string
  kind: component
  metadata:
    properties:
      description:
        nullable: true
        type:
          - string
      group:
        properties:
          maintainers:
            items:
              type: string
            type: array
          product_owner:
            type: string
          project_owner:
            type: string
        type: object
      links:
        items:
          properties:
            icon:
              nullable: true
              type:
                - string
            name:
              type: string
            url:
              type: string
          type: object
        type:
          - array
      name:
        type: string
      owner:
        type: string
      tags:
        items:
          type: string
        type:
          - array
    type: object
  spec:
    properties:
      analysis:
        items:
          properties:
            exclusions:
              items:
                type: string
              type: array
          type: object
        type:
          - array
      environments:
        items:
          properties:
            dashboard_url:
              nullable: true
              type:
                - string
            health_check_url:
              nullable: true
              type:
                - string
            service_urls:
              items:
                type: string
              type: array
          type: object
        type: array
      impact:
        enum:
          - profit
          - customers
          - employees
        type: string
      integrations:
        items:
          properties:
            pagerduty_service:
              type: string
            sentry:
              type: string
            sonarqube_project:
              type: string
          type: object
        type:
          - array
      lifecycle:
        enum:
          - beta
          - production
          - deprecated
          - discontinued
        type: string
      type: service
    type: object
required:
  - kind
  - name
  - owner
  - type
type: object
